spring:
  application:
    name: FirstSecurityApp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_app_db
    username: postgres
    password: Madiyar0105
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true